# -*- coding: utf-8 -*-
"""Урок 1. Получите погоду из терминала (1).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1iIz1fdfxJvoLKdM7pfIAE15PIUSjw9xa
"""

import requests

url = 'https://wttr.in'

def get_weather(countries):
    params = {
        'lang' : 'ru',
        'M':'',
        'm':'',
        'n':'',
        'q':'',
        'T':''
    }
    for place in countries:
        response = requests.get(f'{url}/{place}', params = params)
        response.raise_for_status()
        print(response.text)
    return

def main():
  countries = ['london', 'svo', 'череповец']
  get_weather(countries)

if __name__ == '__main__':
    main()
